"""add payment billing metadata and paypal webhook events

Revision ID: 031f1dce8a4a
Revises: 8877c2e66211
Create Date: 2026-09-18 22:31:10.184644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031f1dce8a4a'
down_revision: Union[str, None] = '8877c2e66211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paypal_webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_paypal_webhook_events_event_id', 'paypal_webhook_events', ['event_id'], unique=False)
    op.create_index('ix_paypal_webhook_events_status', 'paypal_webhook_events', ['status'], unique=False)
    op.add_column('payments', sa.Column('plan', sa.String(length=50), server_default='standard', nullable=False))
    op.add_column('payments', sa.Column('billing_cycle', sa.String(length=20), server_default='monthly', nullable=False))
    op.alter_column('payments', 'plan', server_default=None)
    op.alter_column('payments', 'billing_cycle', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'billing_cycle')
    op.drop_column('payments', 'plan')
    op.drop_index('ix_paypal_webhook_events_status', table_name='paypal_webhook_events')
    op.drop_index('ix_paypal_webhook_events_event_id', table_name='paypal_webhook_events')
    op.drop_table('paypal_webhook_events')
    # ### end Alembic commands ###
